services:
  - type: web
    name: Woolim
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install --upgrade pip wheel setuptools && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
