services:
  - type: web
    name: Woolim
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    packages:
      - ffmpeg
      - libavformat-dev
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libswscale-dev
      - libswresample-dev
      - libavutil-dev
      - pkg-config
